repos:
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3.11

  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        entry: python -m pytest tests/
        language: system
        always_run: true
        files: '^tests/.*\.py$'

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1  # Use the latest revision
    hooks:
      - id: flake8
        # To not hard enforce, you can use `warn: true`
        warn: true

  - repo: local
    hooks:
      - id: pylint
        name: Run pylint  # Add a descriptive name for the hook
        entry: pylint  # Specify how to run pylint, adjust as necessary
        language: system
        files: \.py$  # Run on Python files



  # - repo: https://github.com/timothycrosley/isort
  #   rev: 5.6.4
  #   hooks:
  #     - id: isort
  #       language_version: python3.11

  # - repo: https://github.com/PyCQA/flake8
  #   rev: 3.8.4
  #   hooks:
  #     - id: flake8

  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.6.2
  #   hooks:
  #     - id: bandit

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.782
  #   hooks:
  #     - id: mypy

      # - id: safety
      #   name: safety
      #   entry: safety check
      #   language: system
      #   pass_filenames: false
